#!/bin/bash
  # Copying files

ROOT_UID=0
DEST_DIR=

# Destination directory
if [ "$UID" -eq "$ROOT_UID" ]; then
  DEST_DIR="/usr/share/themes"
else
  DEST_DIR="$HOME/.themes"
fi

repodir=$(cd $(dirname $0) && pwd)
srcdir=${repodir}/src

echo

for variant in 'Dark' 'Light' ; do
  for size in '' '-Laptop' ; do
	for color in '' '-Ruby' '-Doder'; do
		echo -e "   Installing Vimix${variant}${size}${color} ..."

		themedir=$DEST_DIR/Vimix${variant}${size}${color}
		install -d ${themedir}

		# Install index.theme
		cd ${srcdir}
		cp -ur \
			index-${variant}${size}${color}.theme \
			${themedir}/index.theme

		# Install GNOME Shell Theme
		install -d ${themedir}/gnome-shell
		cd ${srcdir}/gnome-shell
		cp -ur \
			extensions \
			no-events.svg \
			no-notifications.svg \
			process-working.svg \
			${themedir}/gnome-shell

		cp -ur \
			assets${color} \
			${themedir}/gnome-shell/assets

		cp -ur \
			gnome${variant}-shell${size}${color}.css \
			${themedir}/gnome-shell/gnome-shell.css

		glib-compile-resources \
			--sourcedir=${themedir}/gnome-shell \
			--target=${themedir}/gnome-shell/gnome-shell-theme.gresource \
			gnome-shell-theme.gresource.xml

		# Install GTK+ 2 Theme
		install -d ${themedir}/gtk-2.0
		cd ${srcdir}/gtk-2.0

		cp -ur \
			Vimix${color}/assets \
			Vimix${color}/apps.rc \
			${themedir}/gtk-2.0

		cp -ur \
			Vimix${color}/main${variant}.rc \
			${themedir}/gtk-2.0/main.rc

		cp -ur \
			Vimix${color}/gtk${variant}rc \
			${themedir}/gtk-2.0/gtkrc

		# Install GTK+ 3 Theme
		install -d ${themedir}/gtk-3.0
		cd ${srcdir}/gtk-3.0
		cp -ur \
			assets${color}/assets \
			${themedir}/gtk-3.0/assets
		cp -ur \
			gtk${variant}${size}${color}.css \
			${themedir}/gtk-3.0/gtk.css
		cp -ur \
			gtk${size}${color}-dark.css \
			${themedir}/gtk-3.0/gtk-dark.css

		# Install Metacity Theme
		install -d ${themedir}/metacity-1
		cd ${srcdir}/metacity-1/Vimix${variant}
		cp -ur \
			*.svg \
			${themedir}/metacity-1

		cp -ur \
			metacity-theme${color}-2.xml \
			${themedir}/metacity-1/metacity-theme-2.xml
		cp -ur \
			metacity-theme${color}-3.xml \
			${themedir}/metacity-1/metacity-theme-3.xml


		# Install Unity Theme
		install -d ${themedir}/unity
		cd ${srcdir}/unity
		cp -ur \
			Vimix${size}/* \
			${themedir}/unity
	done
  done
done

