#!/bin/bash
notify-send "vimix-gtk-themes" "Getting the latest version of the Vimix themes..." -i system-software-update; 
cd /tmp/; 
rm -Rf /tmp/vimix-gtk-themes.zip 2>/dev/null; 
rm -Rf /tmp/vimix-gtk-themes-master/ 2>/dev/null; 
wget https://github.com/vinceliuice/vimix-gtk-themes/archive/master.zip -O vimix-gtk-themes.zip; 
unzip vimix-gtk-themes.zip; 
cd vimix-gtk-themes-master; 
./Install; 
notify-send "All done!" "Enjoy the latest version of Vimix!" -i face-smile
